"""
Download open PDFs listed in CitePaper.csv.

This is Step 4 route B groundwork. It expects CitePaper.csv to include PDF
columns generated by the updated fetch_openalex_citations.py:
    pdf_url, best_oa_pdf_url, oa_url, content_pdf_url, is_oa

It downloads only URL values that look like direct PDFs and writes a manifest.
"""

from __future__ import annotations

import argparse
import csv
import re
import time
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


DEFAULT_INPUT_CSV = "CitePaper.csv"
DEFAULT_OUT_DIR = "open-pdfs"
MANIFEST_NAME = "manifest.csv"
REQUEST_DELAY_SECONDS = 0.25

PDF_URL_COLUMNS = [
    "pdf_url",
    "best_oa_pdf_url",
    "content_pdf_url",
    "oa_url",
]

MANIFEST_FIELDS = [
    "openalex_id",
    "display_name",
    "doi",
    "status",
    "pdf_url",
    "local_path",
    "error",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Download open PDF URLs from a citation CSV.")
    parser.add_argument(
        "--input",
        default=DEFAULT_INPUT_CSV,
        help=f"CSV with PDF URL columns. Default: {DEFAULT_INPUT_CSV}",
    )
    parser.add_argument(
        "--out-dir",
        default=DEFAULT_OUT_DIR,
        help=f"Directory for PDFs and manifest. Default: {DEFAULT_OUT_DIR}",
    )
    parser.add_argument(
        "--max-pdfs",
        type=int,
        default=None,
        help="Stop after this many successful downloads/skips with files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Redownload PDFs even when local files already exist.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=45,
        help="Per-download timeout in seconds. Default: 45.",
    )
    return parser.parse_args()


def load_rows(path: str) -> list[dict[str, str]]:
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def truthy(value: str | None) -> bool:
    return str(value or "").strip().lower() in {"true", "1", "yes"}


def choose_pdf_url(row: dict[str, str]) -> str:
    if "is_oa" in row and row.get("is_oa") and not truthy(row.get("is_oa")):
        return ""

    for column in PDF_URL_COLUMNS:
        url = (row.get(column) or "").strip()
        if looks_like_pdf_url(url):
            return url
    return ""


def looks_like_pdf_url(url: str) -> bool:
    if not url.startswith(("http://", "https://")):
        return False
    lowered = url.lower()
    return ".pdf" in lowered or "/pdf" in lowered or "pdf?" in lowered


def safe_filename(row: dict[str, str]) -> str:
    openalex_id = (row.get("openalex_id") or "").rstrip("/").split("/")[-1]
    if openalex_id:
        return f"{openalex_id}.pdf"

    doi = row.get("doi") or ""
    if doi:
        stem = re.sub(r"[^A-Za-z0-9]+", "_", doi).strip("_")
        return f"{stem[:100]}.pdf"

    title = row.get("display_name") or "paper"
    stem = re.sub(r"[^A-Za-z0-9]+", "_", title).strip("_")
    return f"{stem[:100]}.pdf"


def download_pdf(url: str, path: Path, timeout: int) -> None:
    request = Request(
        url,
        headers={
            "Accept": "application/pdf,*/*",
            "User-Agent": "ReviewerProject/0.1 (open PDF downloader)",
        },
    )
    with urlopen(request, timeout=timeout) as response:
        data = response.read()
    if not data.startswith(b"%PDF"):
        raise ValueError("Downloaded content does not look like a PDF.")
    path.write_bytes(data)


def manifest_row(
    row: dict[str, str],
    *,
    status: str,
    pdf_url: str,
    local_path: str,
    error: str = "",
) -> dict[str, Any]:
    return {
        "openalex_id": row.get("openalex_id", ""),
        "display_name": row.get("display_name", ""),
        "doi": row.get("doi", ""),
        "status": status,
        "pdf_url": pdf_url,
        "local_path": local_path,
        "error": error,
    }


def write_manifest(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=MANIFEST_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = parse_args()
    if args.max_pdfs is not None and args.max_pdfs < 1:
        print("--max-pdfs must be at least 1.")
        return 2

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = load_rows(args.input)
    manifest: list[dict[str, Any]] = []
    completed = 0

    for row in rows:
        pdf_url = choose_pdf_url(row)
        if not pdf_url:
            manifest.append(
                manifest_row(row, status="no_pdf_url", pdf_url="", local_path="")
            )
            continue

        local_path = out_dir / safe_filename(row)
        if local_path.exists() and not args.force:
            manifest.append(
                manifest_row(
                    row,
                    status="skipped_exists",
                    pdf_url=pdf_url,
                    local_path=str(local_path),
                )
            )
            completed += 1
        else:
            try:
                download_pdf(pdf_url, local_path, args.timeout)
                manifest.append(
                    manifest_row(
                        row,
                        status="downloaded",
                        pdf_url=pdf_url,
                        local_path=str(local_path),
                    )
                )
                completed += 1
                time.sleep(REQUEST_DELAY_SECONDS)
            except (HTTPError, URLError, TimeoutError, OSError, ValueError) as exc:
                manifest.append(
                    manifest_row(
                        row,
                        status="failed",
                        pdf_url=pdf_url,
                        local_path=str(local_path),
                        error=str(exc),
                    )
                )

        if args.max_pdfs is not None and completed >= args.max_pdfs:
            break

    manifest_path = out_dir / MANIFEST_NAME
    write_manifest(manifest_path, manifest)
    status_counts: dict[str, int] = {}
    for item in manifest:
        status_counts[item["status"]] = status_counts.get(item["status"], 0) + 1

    print(f"Rows inspected: {len(manifest)}")
    print("Statuses: " + ", ".join(f"{key}={value}" for key, value in status_counts.items()))
    print(f"Saved manifest: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
